version: '3.5'

services:
  database:
    image: postgres:13-alpine
    volumes:
      - db_data:/data/postgres
      - ./env/db-init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'zetto'
      POSTGRES_USER: 'zetto'
      POSTGRES_PASSWORD: 'supersecret'
      PGDATA: /data/postgres

  portofino:
    build: ./portofino/
    ports:
      - '8080:8080'
    environment:
      JWT_SECRET: 'ciaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociao'
      DATABASE_ADDRESS: 'database'
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'zetto'
      DATABASE_USERNAME: 'zetto'
      DATABASE_PASSWORD: 'supersecret'
      PGDATA: /data/postgres
      TZ: 'Europe/Rome'

volumes:
  db_data:
