version: '3.5'

services:
  frontend:
    image: mitto98/tesi-frontend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tesi-fe.rule=Host(`tesi.codemoka.io`)'
    networks:
      - default

  portofino:
    image: mitto98/tesi-portofino
    ports:
      - '8080:8080'
    environment:
      JWT_SECRET: 'ciaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociaociao'
      DATABASE_ADDRESS: 'database'
      DATABASE_PORT: '5432'
      DATABASE_NAME: 'zetto'
      DATABASE_USERNAME: 'zetto'
      DATABASE_PASSWORD: 'supersecret'
      PGDATA: /data/postgres
      TZ: 'Europe/Rome'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.tesi-api.rule=Host(`tesi.codemoka.io`) && PathPrefix(`/api`)'
    networks:
      - default
      - project

  database:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'zetto'
      POSTGRES_USER: 'zetto'
      POSTGRES_PASSWORD: 'supersecret'
      PGDATA: /data/postgres
    volumes:
      - db_data:/data/postgres
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - project

volumes:
  db_data:

networks:
  default:
    external:
      name: gateway
  project:
    internal: true
