name: Main build ci

on:
  push:
    branches: [main]

jobs:
  build-fe:
    name: Build frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup node.js 14
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: frontend
          path: frontend/dist

  build-be:
    name: Build backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: portofino
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v2.1.6
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package
      - uses: actions/upload-artifact@v2
        with:
          name: portofino
          path: ./portofino/target/ROOT.war

  docker-fe:
    name: Build and push frontend docker image
    runs-on: ubuntu-latest
    needs: build-fe
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2
        with:
          name: frontend
          path: ./frontend/dist
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET_KEY }}
      - uses: docker/setup-buildx-action@v1.3.0
      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-mdhrfe-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-mdhrfe-
      - uses: docker/build-push-action@v2.5.0
        with:
          context: ./frontend/
          tags: mitto98/tesi-frontend:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  docker-be:
    name: Build and push backend docker image
    runs-on: ubuntu-latest
    needs: build-be
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/download-artifact@v2
        with:
          name: portofino
          path: ./portofino/target
      - run: |
          ls
          pwd
      - uses: docker/login-action@v1.9.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET_KEY }}
      - uses: docker/setup-buildx-action@v1.3.0
      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-mdhrbe-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-mdhrbe-
      - uses: docker/build-push-action@v2.5.0
        with:
          context: ./portofino/
          tags: mitto98/tesi-portofino:latest
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
